### ISSUE TITLE
file names

### ISSUE THREAD

**Issue by gherardovarando** [ComputationalIntelligenceGroup/MultiMap-documentation#1]
Some imagej task have problems with files names or folder names with spaces.
The doc should state that is better to use folder and files name without spaces.

**Comment by cahernanz** [comment]
- Added the consideration of not using spaces in filenames.

- Added to doc some extra info, and examples of using the extension.

**Comment by gherardovarando** [comment]
- move the consideration of not using spaces in filenames somewhere at the top of the imagejextension doc page
